server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          autoCreateTopics: true
      function:
        definition: messageProducer;messageConsumer
      bindings:
        messageProducer-out-0:
          destination: simple.message.topic
        messageConsumer-in-0:
          destination: simple.message.topic
